DROP TABLE IF EXISTS payments;

CREATE TABLE payments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    currency VARCHAR(4) NOT NULL,
    amount INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT,
    hash VARCHAR (64)
);